### ISSUE TITLE
Guards appear in the company building

### ISSUE THREAD

**Issue by Paradox75831004** [eXish/lc-curseofembrion#1]
Add a config or blacklist for moons so that the curse doesn't work there
At least so that by default there would never be a curse in the company building (maybe this is such a joke, but this is too much xD)

![image](https://github.com/user-attachments/assets/72d94462-3cee-4ba4-82de-d2572259dc41)

![image](https://github.com/user-attachments/assets/30f1fcfc-1ee2-42f7-8857-2ad7f3b8cfae)

**Comment by eXish** [comment]
Fixed as of update 1.1.1
